apiVersion: v1
kind: Service
metadata:
  name: hc-bc-mysql
  labels:
    app: hc-bc
spec:
  selector:
    app: hc-bc
    tier: mysql
  ports:
    - port: 3306
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: hc-bc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: hc-bc-mysql
  labels:
    app: hc-bc
spec:
  selector:
    matchLabels:
      app: hc-bc
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hc-bc
        tier: mysql
    spec:
      containers:
      - image: schmidtp0740/hc-bc-mysql:latest
        name: mysql
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "rootpass"
        - name: "MYSQL_USER"
          value: "dbuser"
        - name: "MYSQL_PASSWORD"
          value: "userpass"
        - name: "MYSQL_DATABASE"
          value: "myimagedb"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
